=== geonetwork/geonetwork/src/shared/schemas/src/main/resources/xml/validation/schema-ident.xsd
<?xml version="1.0" encoding="utf-8"?>
<!--

    (c) 2003 Open Source Geospatial Foundation - all rights reserved
    This code is licensed under the GPL 2.0 license,
    available at the root application directory.

-->

<xs:schema xmlns:gns="http://geonetwork-opensource.org/schemas/schema-ident"
           xmlns:xml="http://www.w3.org/XML/1998/namespace"
           xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsl="http://www.w3.org/2001/XMLSchema"
           version="1.0"
           elementFormDefault="qualified"
           attributeFormDefault="unqualified"
           targetNamespace="http://geonetwork-opensource.org/schemas/schema-ident">

  <xs:import schemaLocation="xml.xsd" namespace="http://www.w3.org/XML/1998/namespace"/>

  <xs:annotation>
    <xs:documentation>
      XML Schema which can be used to validate GeoNetwork schema-ident.xml
      file used in Schema Plugins.
    </xs:documentation>
  </xs:annotation>

  <!-- ====================================================================== -->
  <!-- schema is the root element in a GeoNetwork schema identification -->
  <!-- ====================================================================== -->

  <xs:element name="schema" type="gns:schemaType"/>

  <!-- ====================================================================== -->
  <!-- schemaType complex type -->
  <!-- ====================================================================== -->

  <xs:complexType name="schemaType">
    <xs:annotation>
      <xs:documentation>
        All schema identity files must have the elements defined in this
        type:

        name = unique name of the schema used in GeoNetwork (lower case,
        and if a profile then it should be named after the base schema
        using base-schema-name.profile-name eg. iso19139.mcp)

        id = unique identifier for the schema

        version = official version number of the schema

        depends = names of other schemas that this schema depends on. This
        schema will fail to load if these schemas are not present.

        schemaLocation = official URL of XML schema definitions (XSD) for this
        metadata schema

        autodetect = information used to detect whether a metadata record
        belongs to this schema
      </xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="name" type="xs:string" minOccurs="1"/>
      <xs:element name="id" type="xs:string" minOccurs="1"/>
      <xs:element name="version" type="xs:string" minOccurs="1"/>
      <xs:element name="appMinorVersionSupported" type="xs:string" minOccurs="1"/>
      <xs:element name="appMajorVersionSupported" type="xs:string" minOccurs="0"/>
      <xs:element name="title" type="gns:title" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="description" type="gns:description" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="standardUrl" type="gns:standardUrl" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="depends" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="schemaLocation" type="xs:string" minOccurs="1"/>
      <xs:element name="autodetect" type="gns:autodetectType"
                  minOccurs="1" maxOccurs="1"/>
      <xs:element name="filters" type="gns:filters" minOccurs="0" maxOccurs="1"/>
      <xs:element name="formatters" type="gns:formatters" minOccurs="0" maxOccurs="1"/>
      <xs:element name="readwriteUuid" type="xs:boolean" minOccurs="0" maxOccurs="1"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="title">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute ref="xml:lang"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="description">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute ref="xml:lang"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="standardUrl">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute ref="xml:lang"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <!-- ====================================================================== -->
  <!-- autodetectType complex type -->
  <!-- ====================================================================== -->

  <xs:complexType name="autodetectType">
    <xs:annotation>
      <xs:documentation>
        Define the information used to determine whether a
        metadata record is defined using this schema.
      </xs:documentation>
    </xs:annotation>
    <!-- one and one only rule to detect schemas can be specified -->
    <xs:choice minOccurs="1" maxOccurs="1">
      <xs:element name="elements" type="gns:elementsType"/>
      <xs:element name="attributes" type="gns:attributesType"/>
      <xs:element name="namespaces" type="gns:namespacesType"/>
    </xs:choice>
  </xs:complexType>

  <!-- ====================================================================== -->
  <!-- namespacesType complex type -->
  <!-- ====================================================================== -->

  <xs:simpleType name="namespacesType">
    <xs:annotation>
      <xs:documentation>
        Describes the namespace(s) that must exist in a metadata record for it
        to be identified as belonging to this schema.
      </xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:token"> <!-- no content allowed -->
      <xs:enumeration value=""/>
    </xs:restriction>
  </xs:simpleType>

  <!-- ====================================================================== -->
  <!-- attributesType complex type -->
  <!-- ====================================================================== -->

  <xs:complexType name="attributesType">
    <xs:annotation>
      <xs:documentation>
        Describes the attribute(s) that must exist in a metadata record for it
        to be identified as belonging to this schema.
      </xs:documentation>
    </xs:annotation>
    <xs:anyAttribute namespace="##any" processContents="skip"/>
  </xs:complexType>

  <!-- ====================================================================== -->
  <!-- elementsType complex type -->
  <!-- ====================================================================== -->

  <xs:complexType name="elementsType">
    <xs:annotation>
      <xs:documentation>
        Contains the elements that must exist in a metadata record for it
        to be identified as belonging to this schema.
      </xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:any namespace="##any" processContents="skip" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="type" use="optional">
      <xs:annotation>
        <xs:documentation>
          Determines how the elements specified will be used to detect the
          schema.

          root = the element defined is expected to be the root element

          search = the elements and their content must be present somewhere in
          the record (default if unspecified)
        </xs:documentation>
      </xs:annotation>
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="root"/>
          <xs:enumeration value="search"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:complexType>

  <xs:complexType name="filters">
    <xs:annotation>
      <xs:documentation>
        Define the filter rules to apply to the
        metadata record using this schema by reserved
        operation.

        A maximum of 3 filters could be defined, one for
        each reserved operation editing, download and dynamic.
      </xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="filter" type="gns:filter" minOccurs="1" maxOccurs="3"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="filter">
    <xs:annotation>
      <xs:documentation>A filter define an operation
        to check for the user groups and apply the filter
        defined by the XPath. All elements matching the XPath
        are removed from the record before being returned
        to the user.
      </xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="keepMarkedElement" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>An optional element definition to substitute
            the replaced element by (if a match is found this element
            attributes or children are inserted).
            This is used to highlight removed element.
          </xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:sequence>
            <xs:any namespace="##any" processContents="skip" minOccurs="0" maxOccurs="1"/>
          </xs:sequence>
          <xs:anyAttribute namespace="##any" processContents="skip"/>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="xpath" use="required">
      <xs:annotation>
        <xs:documentation>
          An XPath to select elements to filter. Does not support version 2.0 functions like matches.
        </xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="jsonpath">
      <xs:annotation>
        <xs:documentation>
          An JSON path to select elements to filter in the Elasticsearch index.
        </xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="ifNotOperation" use="required">
      <xs:annotation>
        <xs:documentation>
          An operation (which match canEdit, canDownload, canDynamic method in AccessManager)
        </xs:documentation>
      </xs:annotation>
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="editing"/>
          <xs:enumeration value="download"/>
          <xs:enumeration value="dynamic"/>
          <xs:enumeration value="authenticated" />
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:complexType>

  <xs:complexType name="formatters">
    <xs:annotation>
      <xs:documentation>
        Define the formatters for the metadata records using this schema.
      </xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="formatter" type="gns:formatter" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="formatter">
    <xs:annotation>
      <xs:documentation>A formatter defines an export of the metadata record to another format.
      </xs:documentation>
    </xs:annotation>
    <xs:attribute name="name" use="required">
      <xs:annotation>
        <xs:documentation>
          Formatter name. It should correspond to the formatter folder name of the schema.
        </xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="contentType">
      <xs:annotation>
        <xs:documentation>
          Formatter output content-type.
        </xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>
</xs:schema>

=== geonetwork/geonetwork/src/shared/schemas/src/main/resources/schemas/iso19139.nl.geografie.2.0.0/schema-ident.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    SPDX-FileCopyrightText: 2001 FAO-UN and others <geonetwork@osgeo.org>
    SPDX-License-Identifier: GPL-2.0-or-later

-->

<schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://geonetwork-opensource.org/schemas/schema-ident"
        xsi:schemaLocation="http://geonetwork-opensource.org/schemas/schema-ident http://geonetwork-opensource.org/schemas/schema-ident/schema-ident.xsd">
  <name>iso19139.nl.geografie.2.0.0</name>
  <id>6b76bf55-da03-4b86-acaa-a81bd982e07a</id>
  <version>2.1.0</version>
  <appMinorVersionSupported>4.4.0</appMinorVersionSupported>
  <title xml:lang="en">Dutch metadata profile on ISO 19115 for geography version 2.1.0</title>
  <title xml:lang="nl">Nederlands metadata profiel op ISO 19115 voor geografie versie 2.1.0</title>
  <description>Geonovum ontwikkelt en beheert het Nederlandse metadata profiel voor het beschrijven van geografische datasets. Dit profiel is een verbijzondering van de internationale metadatastandaarden van ISO en is bedoeld om de interoperabiliteit binnen Nederland te bevorderen.</description>
  <standardUrl>https://docs.geostandaarden.nl/md/mdprofiel-iso19115</standardUrl>
  <schemaLocation>http://www.isotc211.org/2005/gmd http://schemas.opengis.net/iso/19139/20060504/gmd/gmd.xsd
                  http://www.isotc211.org/2005/gmx http://schemas.opengis.net/iso/19139/20060504/gmx/gmx.xsd</schemaLocation>
  <autodetect xmlns:gmd="http://www.isotc211.org/2005/gmd"
              xmlns:gco="http://www.isotc211.org/2005/gco">

    <elements>
      <gmd:metadataStandardName>
        <gco:CharacterString>ISO 19115</gco:CharacterString>
      </gmd:metadataStandardName>
      <gmd:metadataStandardVersion>
        <gco:CharacterString>Nederlands metadata profiel op ISO 19115 voor geografie 2.1.0|Nederlands metadata profiel op ISO 19115 voor geografie 2.0|Nederlandse metadata profiel op ISO 19115 voor geografie 2.0|Nederlands metadata profiel op ISO 19115 voor geografie 2.1|Nederlandse metadata profiel op ISO 19115 voor geografie 2.1|Nederlandse metadata profiel op ISO 19115 voor geografie 2.1.0|Nederlands metadata profiel op ISO 19115 voor geografie 2.0.0</gco:CharacterString>
      </gmd:metadataStandardVersion>
    </elements>

  </autodetect>
  <filters xmlns:gco="http://www.isotc211.org/2005/gco">
    <filter xpath="*//*[@gco:nilReason='withheld']"
            ifNotOperation="editing">
      <keepMarkedElement gco:nilReason="withheld"/>
    </filter>
    <filter
      xpath="*//gmd:onLine[*/gmd:protocol/gco:CharacterString = 'WWW:DOWNLOAD-1.0-http--download']"
      ifNotOperation="download"/>
    <filter xpath="*//gmd:onLine[starts-with(*/gmd:protocol/gco:CharacterString, 'OGC:WMS')]"
            ifNotOperation="dynamic"/>
  </filters>
  <formatters>
    <formatter name="xml" title="" officialProfileName="http://geonetwork.net/def/profile/raw-xml" contentType="application/xml"/>
    <formatter name="dcat-ap-nl-3" title="" officialProfileName="http://geonetwork.net/def/profile/dcat-ap-nl-3" contentType="application/rdf+xml"/>
    <formatter name="jsonld" title="" officialProfileName="http://geonetwork.net/def/profile/jsonld" contentType="application/json"/>
    <formatter name="iso19139" title="" officialProfileName="http://geonetwork.net/def/profile/iso19139" contentType="application/xml"/>
    <formatter name="iso19115-3.2018" title="" officialProfileName="http://geonetwork.net/def/profile/iso19115-3.2018" contentType="application/xml"/>
  </formatters>
</schema>

=== geonetwork/geonetwork/src/shared/schemas/src/main/resources/schemas/iso19139.nl.services.2.0.0/schema-ident.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    SPDX-FileCopyrightText: 2001 FAO-UN and others <geonetwork@osgeo.org>
    SPDX-License-Identifier: GPL-2.0-or-later

-->

<schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://geonetwork-opensource.org/schemas/schema-ident"
        xsi:schemaLocation="http://geonetwork-opensource.org/schemas/schema-ident http://geonetwork-opensource.org/schemas/schema-ident/schema-ident.xsd">
  <name>iso19139.nl.services.2.0.0</name>
  <id>fd0615d2-ff7f-43ad-908e-f9ed774a34e5</id>
  <version>2.1.0</version>
  <appMinorVersionSupported>4.4.0</appMinorVersionSupported>
  <title xml:lang="en">Dutch metadata profile on ISO 19119 for services version 2.1.0</title>
  <title xml:lang="nl">Nederlands metadata profiel op ISO 19119 voor services versie 2.1.0</title>
  <description>Geonovum ontwikkelt en beheert het Nederlandse metadata profiel voor het beschrijven van services waarin geografische datasets ontsloten worden. Dit profiel is een verbijzondering van de internationale metadatastandaarden van ISO en is bedoeld om de interoperabiliteit binnen Nederland te bevorderen.</description>
  <standardUrl>https://docs.geostandaarden.nl/md/mdprofiel-iso19119</standardUrl>
  <depends>iso19139</depends>
  <schemaLocation>http://www.isotc211.org/2005/gmd http://schemas.opengis.net/csw/2.0.2/profiles/apiso/1.0.0/apiso.xsd</schemaLocation>
  <autodetect xmlns:gmd="http://www.isotc211.org/2005/gmd"
              xmlns:gco="http://www.isotc211.org/2005/gco">


    <elements>
      <gmd:metadataStandardName>
        <gco:CharacterString>ISO 19119</gco:CharacterString>
      </gmd:metadataStandardName>
      <gmd:metadataStandardVersion>
        <gco:CharacterString>Nederlands metadata profiel op ISO 19119 voor services 2.1.0|Nederlandse metadata profiel op ISO 19119 voor services 2.1.0|Nederlands metadata profiel op ISO 19119 voor services 2.0|Nederlandse metadata profiel op ISO 19119 voor services 2.0</gco:CharacterString>
      </gmd:metadataStandardVersion>
    </elements>

  </autodetect>
  <filters xmlns:gco="http://www.isotc211.org/2005/gco">
    <filter xpath="*//*[@gco:nilReason='withheld']"
            ifNotOperation="editing">
      <keepMarkedElement gco:nilReason="withheld"/>
    </filter>
    <filter
      xpath="*//gmd:onLine[*/gmd:protocol/gco:CharacterString = 'download']"
      ifNotOperation="download"/>
    <filter xpath="*//gmd:onLine[starts-with(*/gmd:protocol/gco:CharacterString, 'OGC:WMS')]"
            ifNotOperation="dynamic"/>
  </filters>
  <formatters>
    <formatter name="xml" title="" officialProfileName="http://geonetwork.net/def/profile/raw-xml" contentType="application/xml"/>
    <formatter name="dcat-ap-nl-3" title="" officialProfileName="http://geonetwork.net/def/profile/dcat-ap-nl-3" contentType="application/rdf+xml"/>
    <formatter name="jsonld" title="" officialProfileName="http://geonetwork.net/def/profile/jsonld" contentType="application/json"/>
    <formatter name="iso19139" title="" officialProfileName="http://geonetwork.net/def/profile/iso19139" contentType="application/xml"/>
    <formatter name="iso19115-3.2018" title="" officialProfileName="http://geonetwork.net/def/profile/iso19115-3.2018" contentType="application/xml"/>
  </formatters>
</schema>
